---
release: 2026.2
election_type: combined
tag: to-be-released
tc_seats: 5
timeframe:
  name: 2025.2-2026.1
  start: 2025-03-14T00:00
  end: 2026-02-18T00:00
  email_deadline: 2026-02-18T00:00
timeline:
  - name: TC Nominations
    start: 2026-02-04T23:45
    end: 2026-02-18T23:45
  - name: PTL Nominations
    start: 2026-02-04T23:45
    end: 2026-02-18T23:45
  - name: TC Campaigning
    start: 2026-02-18T23:45
    end: 2026-02-25T23:45
  - name: TC Election
    start: 2026-02-25T23:45
    end: 2026-03-18T23:45
  - name: PTL Election
    start: 2026-02-25T23:45
    end: 2026-03-18T23:45
